# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_ForwardBackward_AC <- function(N, K, Nstates, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, p_move) {
    .Call('_scrrw_C_ForwardBackward_AC', PACKAGE = 'scrrw', N, K, Nstates, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, p_move)
}

C_ForwardBackward_RW <- function(N, K, Nstates, tr_b4_occ, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_mat) {
    .Call('_scrrw_C_ForwardBackward_RW', PACKAGE = 'scrrw', N, K, Nstates, tr_b4_occ, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_mat)
}

C_ForwardBackward_RWAC <- function(N, K, nCells, nACCells, tr_b4_occ, mu_init, p_init_state_full, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_mat) {
    .Call('_scrrw_C_ForwardBackward_RWAC', PACKAGE = 'scrrw', N, K, nCells, nACCells, tr_b4_occ, mu_init, p_init_state_full, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_mat)
}

C_ForwardBackward_CRW <- function(N, K, nCells, tr_b4_occ, mu_init, p_init_state_full, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_mat) {
    .Call('_scrrw_C_ForwardBackward_CRW', PACKAGE = 'scrrw', N, K, nCells, tr_b4_occ, mu_init, p_init_state_full, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_mat)
}

C_ForecastObs_AC <- function(N, K, Nstates, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, p_move, FBProbs) {
    .Call('_scrrw_C_ForecastObs_AC', PACKAGE = 'scrrw', N, K, Nstates, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, p_move, FBProbs)
}

C_ForecastObs_RW <- function(N, K, Nstates, tr_b4_occ, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_mat, FBProbs) {
    .Call('_scrrw_C_ForecastObs_RW', PACKAGE = 'scrrw', N, K, Nstates, tr_b4_occ, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_mat, FBProbs)
}

C_ForecastObs_RWAC <- function(N, K, nCells, nACCells, tr_b4_occ, mu_init, FBProbs, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_mat) {
    .Call('_scrrw_C_ForecastObs_RWAC', PACKAGE = 'scrrw', N, K, nCells, nACCells, tr_b4_occ, mu_init, FBProbs, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_mat)
}

C_ForecastObs_CRW <- function(N, K, nCells, tr_b4_occ, mu_init, FBProbs, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_mat) {
    .Call('_scrrw_C_ForecastObs_CRW', PACKAGE = 'scrrw', N, K, nCells, tr_b4_occ, mu_init, FBProbs, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_mat)
}

C_ForecastState_AC <- function(N, K, Nstates, y_pix, p_move, FBProbs) {
    .Call('_scrrw_C_ForecastState_AC', PACKAGE = 'scrrw', N, K, Nstates, y_pix, p_move, FBProbs)
}

C_ForecastState_RW <- function(N, K, Nstates, tr_b4_occ, y_pix, t_mat, FBProbs) {
    .Call('_scrrw_C_ForecastState_RW', PACKAGE = 'scrrw', N, K, Nstates, tr_b4_occ, y_pix, t_mat, FBProbs)
}

C_ForecastState_RWAC <- function(N, K, nCells, nACCells, tr_b4_occ, mu_init, FBProbs, y_pix, t_mat) {
    .Call('_scrrw_C_ForecastState_RWAC', PACKAGE = 'scrrw', N, K, nCells, nACCells, tr_b4_occ, mu_init, FBProbs, y_pix, t_mat)
}

C_ForecastState_CRW <- function(N, K, nCells, tr_b4_occ, mu_init, FBProbs, y_pix, t_mat) {
    .Call('_scrrw_C_ForecastState_CRW', PACKAGE = 'scrrw', N, K, nCells, tr_b4_occ, mu_init, FBProbs, y_pix, t_mat)
}

C_pDots_RWAC <- function(K, tr_b4_occ, nCells, nACCells, p_init_state_full, pMove, p_no_det_occ) {
    .Call('_scrrw_C_pDots_RWAC', PACKAGE = 'scrrw', K, tr_b4_occ, nCells, nACCells, p_init_state_full, pMove, p_no_det_occ)
}

C_pDots_CRW <- function(K, tr_b4_occ, nCells, p_init_state_full, pMove, p_no_det_occ) {
    .Call('_scrrw_C_pDots_CRW', PACKAGE = 'scrrw', K, tr_b4_occ, nCells, p_init_state_full, pMove, p_no_det_occ)
}

C_erf <- function(x) {
    .Call('_scrrw_C_erf', PACKAGE = 'scrrw', x)
}

Intermediate_LT_Halfnorm_det <- function(x, y, b, m, sigma) {
    .Call('_scrrw_Intermediate_LT_Halfnorm_det', PACKAGE = 'scrrw', x, y, b, m, sigma)
}

LineTransect_HalfNorm_det <- function(xBounds, yBounds, b, m, sigmaDet, p0) {
    .Call('_scrrw_LineTransect_HalfNorm_det', PACKAGE = 'scrrw', xBounds, yBounds, b, m, sigmaDet, p0)
}

EndPoint_HalfNorm_det <- function(xBounds, yBounds, epX, epY, sigmaDet, p0) {
    .Call('_scrrw_EndPoint_HalfNorm_det', PACKAGE = 'scrrw', xBounds, yBounds, epX, epY, sigmaDet, p0)
}

HazardDetIntgrl_TL <- function(sigmaDet, p0, beta, b, m, Lwr, Upr) {
    .Call('_scrrw_HazardDetIntgrl_TL', PACKAGE = 'scrrw', sigmaDet, p0, beta, b, m, Lwr, Upr)
}

HazardDetIntgrl_EP <- function(sigmaDet, p0, beta, xEP, yEP, Lwr, Upr) {
    .Call('_scrrw_HazardDetIntgrl_EP', PACKAGE = 'scrrw', sigmaDet, p0, beta, xEP, yEP, Lwr, Upr)
}

C_pMove_Normal_Full <- function(K, nCells, habitat, distMat, betaMoves, covarCols, nCovars) {
    .Call('_scrrw_C_pMove_Normal_Full', PACKAGE = 'scrrw', K, nCells, habitat, distMat, betaMoves, covarCols, nCovars)
}

C_pMove_SLTA_Full <- function(K, nCells, distMat, angleMat, alpha, beta, mu, gamma) {
    .Call('_scrrw_C_pMove_SLTA_Full', PACKAGE = 'scrrw', K, nCells, distMat, angleMat, alpha, beta, mu, gamma)
}

C_pMove_SL_Full <- function(K, nCells, habitat, distMat, angleMat, betaMoves, covarCols, nCovars, alpha, beta, pi) {
    .Call('_scrrw_C_pMove_SL_Full', PACKAGE = 'scrrw', K, nCells, habitat, distMat, angleMat, betaMoves, covarCols, nCovars, alpha, beta, pi)
}

C_pMove_Laplace_Full <- function(K, nCells, habitat, distMat, betaMoves, covarCols, nCovars) {
    .Call('_scrrw_C_pMove_Laplace_Full', PACKAGE = 'scrrw', K, nCells, habitat, distMat, betaMoves, covarCols, nCovars)
}

C_pMove_Laplace_Open_move <- function(K, nCells, nCells_aug, habitat, distMat, habitat_aug, distMat_aug, betaMoves, covarCols, nCovars) {
    .Call('_scrrw_C_pMove_Laplace_Open_move', PACKAGE = 'scrrw', K, nCells, nCells_aug, habitat, distMat, habitat_aug, distMat_aug, betaMoves, covarCols, nCovars)
}

C_pMove_RWAC_Laplace_Full <- function(nCells, nACCells, habitat, betaMoves, covarCols, nCovars, rho) {
    .Call('_scrrw_C_pMove_RWAC_Laplace_Full', PACKAGE = 'scrrw', nCells, nACCells, habitat, betaMoves, covarCols, nCovars, rho)
}

C_pMove_CorrelatedRW_Laplace_Full <- function(nCells, habitat, betaMoves, covarCols, nCovars, rotation) {
    .Call('_scrrw_C_pMove_CorrelatedRW_Laplace_Full', PACKAGE = 'scrrw', nCells, habitat, betaMoves, covarCols, nCovars, rotation)
}

C_pMove_RWAC_Laplace_Initial <- function(nCells, nACCells, habitat, distMat_AC, betaMoves, covarCols, nCovars, p_init_state_ac) {
    .Call('_scrrw_C_pMove_RWAC_Laplace_Initial', PACKAGE = 'scrrw', nCells, nACCells, habitat, distMat_AC, betaMoves, covarCols, nCovars, p_init_state_ac)
}

C_pMove_CorrelatedRW_Laplace_Initial <- function(nCells, habitat, distMat, betaMoves, covarCols, nCovars, p_init_state) {
    .Call('_scrrw_C_pMove_CorrelatedRW_Laplace_Initial', PACKAGE = 'scrrw', nCells, habitat, distMat, betaMoves, covarCols, nCovars, p_init_state)
}

C_pDet_Full <- function(K_tot, nCells, nDetCells, lines_arr, detGrid, sigmaDets, g0s, hSigmas, hBetas, detArea, truncDist, SDcols, nSDcols, g0cols, nG0cols, hscols, nhscols, hbcols, nhbcols) {
    .Call('_scrrw_C_pDet_Full', PACKAGE = 'scrrw', K_tot, nCells, nDetCells, lines_arr, detGrid, sigmaDets, g0s, hSigmas, hBetas, detArea, truncDist, SDcols, nSDcols, g0cols, nG0cols, hscols, nhscols, hbcols, nhbcols)
}

C_pNoDet <- function(nCells, K, pDet, pMove) {
    .Call('_scrrw_C_pNoDet', PACKAGE = 'scrrw', nCells, K, pDet, pMove)
}

C_pNoDet_RW <- function(K, tr_b4_occ, nCells, p_init_state, pMove, p_no_det_occ) {
    .Call('_scrrw_C_pNoDet_RW', PACKAGE = 'scrrw', K, tr_b4_occ, nCells, p_init_state, pMove, p_no_det_occ)
}

C_pNoDet_RWAC <- function(K, tr_b4_occ, nCells, nACCells, p_init_state_full, pMove, p_no_det_occ) {
    .Call('_scrrw_C_pNoDet_RWAC', PACKAGE = 'scrrw', K, tr_b4_occ, nCells, nACCells, p_init_state_full, pMove, p_no_det_occ)
}

C_pNoDet_CorrelatedRW <- function(K, tr_b4_occ, nCells, p_init_state_full, pMove, p_no_det_occ) {
    .Call('_scrrw_C_pNoDet_CorrelatedRW', PACKAGE = 'scrrw', K, tr_b4_occ, nCells, p_init_state_full, pMove, p_no_det_occ)
}

C_indLklhd_RandomWalk <- function(N, K, Nstates, tr_b4_occ, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_mat) {
    .Call('_scrrw_C_indLklhd_RandomWalk', PACKAGE = 'scrrw', N, K, Nstates, tr_b4_occ, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_mat)
}

C_indLklhd_AC <- function(N, K, Nstates, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, p_move) {
    .Call('_scrrw_C_indLklhd_AC', PACKAGE = 'scrrw', N, K, Nstates, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, p_move)
}

C_indLklhd_RWAC <- function(N, K, nCells, nACCells, tr_b4_occ, mu_init, p_init_state_full, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_mat) {
    .Call('_scrrw_C_indLklhd_RWAC', PACKAGE = 'scrrw', N, K, nCells, nACCells, tr_b4_occ, mu_init, p_init_state_full, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_mat)
}

C_indLklhd_CorrelatedRW <- function(N, K, nCells, tr_b4_occ, mu_init, p_init_state_full, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_mat) {
    .Call('_scrrw_C_indLklhd_CorrelatedRW', PACKAGE = 'scrrw', N, K, nCells, tr_b4_occ, mu_init, p_init_state_full, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_mat)
}

C_indLklhd_RandomWalk_RWGroup <- function(N, K, Nstates, tr_b4_occ, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_mat, g0s_wCalf, y_group, p_no_det_occ_wCalf, t_mat_wCalf, p_birth, y_sex, other_states, preg_states, wCalf_states, male_states) {
    .Call('_scrrw_C_indLklhd_RandomWalk_RWGroup', PACKAGE = 'scrrw', N, K, Nstates, tr_b4_occ, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_mat, g0s_wCalf, y_group, p_no_det_occ_wCalf, t_mat_wCalf, p_birth, y_sex, other_states, preg_states, wCalf_states, male_states)
}

C_indLklhd_3states <- function(N, K, Nstates, tr_b4_occ, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, p_move_reside, p_move_south, p_move_north, emigration, first_loc_south, gamma, phi, p_reside, south_states, reside_states, north_states, out_states, nCells) {
    .Call('_scrrw_C_indLklhd_3states', PACKAGE = 'scrrw', N, K, Nstates, tr_b4_occ, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, p_move_reside, p_move_south, p_move_north, emigration, first_loc_south, gamma, phi, p_reside, south_states, reside_states, north_states, out_states, nCells)
}

C_indLklhd_3states_moveDirObs <- function(N, K, Nstates, tr_b4_occ, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, p_move_reside, p_move_south, p_move_north, emigration, first_loc_south, gamma, phi, p_reside, south_states, reside_states, north_states, out_states, nCells, migrate_obs, no_move_migrate_obs, ew_migrate_obs, no_move_reside_obs, news_reside_obs, y_dir) {
    .Call('_scrrw_C_indLklhd_3states_moveDirObs', PACKAGE = 'scrrw', N, K, Nstates, tr_b4_occ, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, p_move_reside, p_move_south, p_move_north, emigration, first_loc_south, gamma, phi, p_reside, south_states, reside_states, north_states, out_states, nCells, migrate_obs, no_move_migrate_obs, ew_migrate_obs, no_move_reside_obs, news_reside_obs, y_dir)
}

C_indLklhd_RandomWalk_Direction <- function(N, K, Nstates, tr_b4_occ, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, pMove_North, pMove_West, pMove_South, pMove_East, north_cells, west_cells, south_cells, east_cells, out1_cell, out2_cell, cov_open_transitions, p_nsns, p_nsew, p_nssn, p_ewew, p_ewns, p_ewwe, phi, gamma, D_bars, D_xs, open_transitions) {
    .Call('_scrrw_C_indLklhd_RandomWalk_Direction', PACKAGE = 'scrrw', N, K, Nstates, tr_b4_occ, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, pMove_North, pMove_West, pMove_South, pMove_East, north_cells, west_cells, south_cells, east_cells, out1_cell, out2_cell, cov_open_transitions, p_nsns, p_nsew, p_nssn, p_ewew, p_ewns, p_ewwe, phi, gamma, D_bars, D_xs, open_transitions)
}

C_indLklhd_OpenAC <- function(N, K, Nstates, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_arr, K_sec, p_move, K_covar, nCells) {
    .Call('_scrrw_C_indLklhd_OpenAC', PACKAGE = 'scrrw', N, K, Nstates, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_arr, K_sec, p_move, K_covar, nCells)
}

C_RandomWalk_ReturnState <- function(N, K, Nstates, tr_b4_occ, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_mat) {
    .Call('_scrrw_C_RandomWalk_ReturnState', PACKAGE = 'scrrw', N, K, Nstates, tr_b4_occ, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_mat)
}

C_OpenAC_ReturnState <- function(N, K, Nstates, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_arr, K_sec, p_move, K_covar, nCells) {
    .Call('_scrrw_C_OpenAC_ReturnState', PACKAGE = 'scrrw', N, K, Nstates, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, t_arr, K_sec, p_move, K_covar, nCells)
}

C_RandomWalk_Direction_ReturnState <- function(N, K, Nstates, tr_b4_occ, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, pMove_North, pMove_West, pMove_South, pMove_East, north_cells, west_cells, south_cells, east_cells, out1_cell, out2_cell, cov_open_transitions, p_nsns, p_nsew, p_nssn, p_ewew, p_ewns, p_ewwe, phi, gamma, D_bars, D_xs, open_transitions) {
    .Call('_scrrw_C_RandomWalk_Direction_ReturnState', PACKAGE = 'scrrw', N, K, Nstates, tr_b4_occ, mu_init, y, y_pix, detDists, y_platform, y_ds_covar, y_g0_covar, y_hs_covar, y_hb_covar, n_ds_covars, n_g0_covars, n_hs_covars, n_hb_covars, g0s, sigmaDets, Hsigmas, Hbetas, p_no_det_occ, pMove_North, pMove_West, pMove_South, pMove_East, north_cells, west_cells, south_cells, east_cells, out1_cell, out2_cell, cov_open_transitions, p_nsns, p_nsew, p_nssn, p_ewew, p_ewns, p_ewwe, phi, gamma, D_bars, D_xs, open_transitions)
}

rcpparma_hello_world <- function() {
    .Call('_scrrw_rcpparma_hello_world', PACKAGE = 'scrrw')
}

rcpparma_outerproduct <- function(x) {
    .Call('_scrrw_rcpparma_outerproduct', PACKAGE = 'scrrw', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_scrrw_rcpparma_innerproduct', PACKAGE = 'scrrw', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_scrrw_rcpparma_bothproducts', PACKAGE = 'scrrw', x)
}

